config/routes.rb
Omrails::Application.routes.draw do
  resources :pins
  devise_for :users
  get 'about' => 'pages#about'
  root :to => 'pins#index'
  get 'user_pins' => 'pins#user_pins'

  

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible :city, :state, :zip, :address, :lat, :lng

	has_many :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	attr_accessible :description, :image, :image_remote_url
	has_attached_file :image,
    :storage => :dropbox,
    :dropbox_credentials => { app_key: ENV['APP_KEY'],
                              app_secret: ENV['APP_SECRET'],
                              access_token: ENV['ACCESS_TOKEN'],
                              access_token_secret: ENV['ACCESS_TOKEN_SECRET'],
                              user_id: ENV['USER_ID'],
                              access_type: 'app_folder'}

	validates :image, presence: true
	validates :description, presence: true
	validates :user_id, presence: true
	validates_attachment :image, presence: true,
								content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
								size: { less_than: 5.megabytes }
	belongs_to :user
			has_attached_file :image,
			:styles => { :medium => "300x300>", :thumb => "100x100" }

	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
          :rememberable, :trackable, :validatable
	attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :provider, :uid, :as => [:default, :admin]

	has_many :pins, :dependent => :destroy
	
	validates :name, presence: true
	
	acts_as_followable
	acts_as_follower

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    # With pagination from will_paginate gem
    @pins = Pin.order("created_at DESC").page(params[:page]).per_page(20)
    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @pins }
      format.js
    end
  end

  def show
    @pin = Pin.find(params[:id])
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
    @pin = current_user.pins.find(params[:id])
  end

  def create
    @pin = current_user.pins.build(params[:pin])
      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.'
      else
        render action: 'new'  
      end
  end

  def update
    @pin = current_user.pins.find(params[:id])
      if @pin.update_attributes(params[:pin])
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        render action: 'edit'
      end
  end

  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy
      redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		by <%= link_to "Neil Gehani", "http://twitter.com/GehaniNeil" %>
	</small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
   <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button> 
      <a class="navbar-brand"
        <%= link_to "Social Butterfly", root_path, class: "navbar-brand" %>
       </a>
    </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li>
              <%= link_to new_pin_path do %>
                <span class="glyphicon glyphicon-plus-sign" ></span> New
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>  
              <ul class="dropdown-menu">
                  <li>
                    <%= link_to edit_user_registration_path do %>
                      <span class="glyphicon glyphicon-user"></span> Account Settings
                    <% end %>
                  </li>
                  <li><%= link_to "My Pins", user_pins_path %></li>
                </ul>
            </li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Log in',  new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- .container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Social Butterfly</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<%= render 'layouts/header' %>
		
		<div class="container">
			<% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
			<%= yield %>
			<div class="container">
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Social Butterfly</h1>
	<p>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	</p>
</div>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  <%= link_to "One Month Rails", "http://onemonthrails.com" %>
  is a project to teach 
  <%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
  in one month. This is the sample application.
</p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Enter the image URL" %>
    <%= f.text_field :image_remote_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box panel panel-default">
	<%= link_to image_tag(pin.image.url(:medium)), pin %>
	<div class="panel-body">
		<%= pin.description %>
		<strong><%= pin.user.name if pin.user %></strong>
		<% if current_user == pin.user %>
		<div class="actions">
			<%= link_to edit_pin_path(pin) do %>
				<span class="glyphicon glyphicon-edit"></span> Edit
      <% end %>
			<%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
				<span class="glyphicon glyphicon-remove-circle"></span> Remove
      <% end %>
		</div>
		<% end %>
	</div>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%# render includes partials that begin with _*.html.erb %>
<%# means look in pages subfolder for _home.html.erb %>
<%= render 'pages/home' unless user_signed_in? %>
<div id="pins" class="transitions-enabled">
  <%= render @pins %>
</div> 

<div id="view_paginate">
	<div class="center">
		<%= will_paginate @pins %>
	</div>
</div>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>
<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading center">
                <%= image_tag @pin.image.url(:medium) %>
            </div>
            <div class="panel-body">
                <p><%= @pin.description %></p>
                <p><strong><%= @pin.user.name  if @pin.user %></strong></p>
    			<% if current_user == @pin.user %>
                    <%= link_to edit_pin_path(@pin) do %>
                        <span class="glyphicon glyphicon-edit"></span> Change
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/pins/show.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/pins/user_pins.html.erb
<%# render includes partials that begin with _*.html.erb %>
<%# means look in pages subfolder for _home.html.erb %>
<%= render 'pages/home' unless user_signed_in? %>
<div id="pins" class="transitions-enabled">
	<% if user_signed_in? %>
  	<%= render current_user.pins %>
  <% end %>
</div> 